baseURL = 'https://7timothyhn.github.io/TAIMA.github.io/' ## the main derectory that the website will be published
languageCode = 'en-us' ## set the language to us english
title = 'The Adventures in the Modern Animal Kingdom' ## the main title of the page
theme = 'ananke' ## sets the theme

Paginate = 5

[params]
 
  enableSearch = "true" ## enable search mode
  darkModeToggle = "true" ## enable darkmode


[languages]
  [languages.en]
    title = "Home" ## sets the top right title in the tabs
    contentDir = "content/en" ## sets the main sourse of information 
   


